---
title: "Bootstrapping selection estimates"
output: 
  github_document:
    toc: true
header-includes: >
  \usepackage{lipsum}
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir='../',
                     fig_path="../figs/")
```

``` {r library, message = FALSE, warning = FALSE}
#This is a cohesive list of all the libraries used in this document
library(knitr)
# To install spfTools:
# devtools::install_github("https://github.com/spflanagan/spfTools/")
library(spfTools)
```

```{r load-functions}

set.seed(2025)
num_bootstraps<-1000 #change this as needed
source("R/partition_I.R")
source("R/bootstrap_partition_I.R")
source("R/calc_selection_diffs.R")
source("R/bootstrap_s.R")

```


## Read in the datasets

``` {r read-floridae-data, message = FALSE, warning = FALSE}
fem_succFL <- read.csv("data/floridae_fem_succ.csv")
mal_succFL <- read.csv("data/floridae_mal_succ.csv")
```
``` {r read-fuscus-data, message = FALSE, warning = FALSE}
fem_succFU <- read.csv("data/fuscus_fem_succ.csv")
mal_succFU <- read.csv("data/fuscus_mal_succ.csv")
```
``` {r read-scovelli-data, message = FALSE, warning = FALSE}
fem_succSC <- read.csv("data/scovelli_fem_succ.csv")
mal_succSC <- read.csv("data/scovelli_mal_succ.csv")
```


## Opportunity for selection 

### Partitioning *I* for all individuals

```{r boot-floridae, eval=FALSE}
boot_floridae <- bootstrap_partition_I(num_bootstraps,
                                       fem_succFL,
                                       mal_succFL)
write.csv(boot_floridae, "data/floridae_bootstrapped_I_partitions.csv",
          quote=FALSE, row.names = FALSE)
```
```{r get-floridae-boot}
boot_floridae<-read.csv("data/floridae_bootstrapped_I_partitions.csv")
```


```{r boot-fuscus, eval=FALSE}

boot_fuscus <- bootstrap_partition_I(num_bootstraps,
                                       fem_succFU,
                                       mal_succFU)
write.csv(boot_fuscus, "data/fuscus_bootstrapped_I_partitions.csv",
          quote=FALSE, row.names = FALSE)
```
```{r get-fuscus-boot}
boot_fuscus<-read.csv("data/fuscus_bootstrapped_I_partitions.csv")
```


```{r boot-scovelli, eval=FALSE}

boot_scovelli <- bootstrap_partition_I(num_bootstraps,
                                       fem_succSC,
                                       mal_succSC)
write.csv(boot_scovelli, "data/scovelli_bootstrapped_I_partitions.csv",
          quote=FALSE, row.names = FALSE)
```
```{r get-scovelli-boot}
boot_scovelli<-read.csv("data/scovelli_bootstrapped_I_partitions.csv")
```


#### Generating summary statistics from bootstraps

```{r calc-cis-function}
#Function to calculate confidence intervals from bootstrap results - employing percentile-based
#confidence intervals

calculate_CIs <- function(boot_results, conf_level = 0.95){
  
  alpha <- 1 - conf_level
  
  #Calculate percentile-based confidence intervals
  CIs <- apply(boot_results, 2, function(x){

    c(mean = mean(x),
      lower = quantile(x, alpha/2, na.rm = TRUE),
      upper = quantile(x, 1 - alpha/2, na.rm = TRUE))
    
  })
  
  return(t(CIs))
}
```

```{r calc-CIs}

floridae_CIs <- calculate_CIs(boot_floridae)
fuscus_CIs <- calculate_CIs(boot_fuscus)
scovelli_CIs <- calculate_CIs(boot_scovelli)

```

```{r show-fem-cis}

female_CIs <- as.data.frame(rbind(floridae_CIs[grep("fem", rownames(floridae_CIs)), ],
                    fuscus_CIs[grep("fem", rownames(fuscus_CIs)), ],
                    scovelli_CIs[grep("fem", rownames(scovelli_CIs)), ]))

female_CIs$species <- c(rep("floridae", times = nrow(floridae_CIs[grep("fem", rownames(floridae_CIs)),])),
                        rep("fuscus", times = nrow(fuscus_CIs[grep("fem", rownames(fuscus_CIs)),])),
                        rep("scovelli", times = nrow(scovelli_CIs[grep("fem", rownames(scovelli_CIs)),])))

kable(round(female_CIs[,colnames(female_CIs) != "species"],6))

```

```{r show-mal-cis}

male_CIs <- as.data.frame(rbind(floridae_CIs[grep("mal", rownames(floridae_CIs)), ],
                  fuscus_CIs[grep("mal", rownames(fuscus_CIs)), ],
                  scovelli_CIs[grep("mal", rownames(scovelli_CIs)), ]))

male_CIs$species <- c(rep("floridae", times = nrow(floridae_CIs[grep("mal", rownames(floridae_CIs)),])),
                      rep("fuscus", times = nrow(fuscus_CIs[grep("mal", rownames(fuscus_CIs)),])),
                      rep("scovelli", times = nrow(scovelli_CIs[grep("mal", rownames(scovelli_CIs)),])))

male_CIs[,1:3]<-round(male_CIs[,1:3],6)
kable(male_CIs)

```

## Selection differentials

```{r boot-floridae-s, eval=FALSE}
boot_floridae <- bootstrap_s(num_bootstraps,
                                       fem_succFL,
                                       mal_succFL)
write.csv(boot_floridae, "data/floridae_bootstrapped_s.csv",
          quote=FALSE, row.names = FALSE)
```
```{r get-floridae-boot-s}
boot_floridae<-read.csv("data/floridae_bootstrapped_s.csv")
```


```{r boot-fuscus-s, eval=FALSE}

boot_fuscus <- bootstrap_s(num_bootstraps,
                                       fem_succFU,
                                       mal_succFU)
write.csv(boot_fuscus, "data/fuscus_bootstrapped_s.csv",
          quote=FALSE, row.names = FALSE)
```
```{r get-fuscus-boot-s}
boot_fuscus<-read.csv("data/fuscus_bootstrapped_s.csv")
```


```{r boot-scovelli-s, eval=FALSE}

boot_scovelli <- bootstrap_s(num_bootstraps,
                                       fem_succSC,
                                       mal_succSC)
write.csv(boot_scovelli, "data/scovelli_bootstrapped_s.csv",
          quote=FALSE, row.names = FALSE)
```
```{r get-scovelli-boot-s}
boot_scovelli<-read.csv("data/scovelli_bootstrapped_s.csv")
```

#### Generating summary statistics for selection differentials

```{r calc-CIs-sd}

floridae_CIs <- calculate_CIs(boot_floridae)
fuscus_CIs <- calculate_CIs(boot_fuscus)
scovelli_CIs <- calculate_CIs(boot_scovelli)

```

```{r show-fem-cis-sd}

female_CIs <- as.data.frame(rbind(floridae_CIs[grep("fem", rownames(floridae_CIs)), ],
                    fuscus_CIs[grep("fem", rownames(fuscus_CIs)), ],
                    scovelli_CIs[grep("fem", rownames(scovelli_CIs)), ]))

female_CIs$species <- c(rep("floridae", times = nrow(floridae_CIs[grep("fem", rownames(floridae_CIs)),])),
                        rep("fuscus", times = nrow(fuscus_CIs[grep("fem", rownames(fuscus_CIs)),])),
                        rep("scovelli", times = nrow(scovelli_CIs[grep("fem", rownames(scovelli_CIs)),])))

kable(round(female_CIs[,colnames(female_CIs) != "species"],6))

```

```{r show-mal-cis-sd}

male_CIs <- as.data.frame(rbind(floridae_CIs[grep("mal", rownames(floridae_CIs)), ],
                  fuscus_CIs[grep("mal", rownames(fuscus_CIs)), ],
                  scovelli_CIs[grep("mal", rownames(scovelli_CIs)), ]))

male_CIs$species <- c(rep("floridae", times = nrow(floridae_CIs[grep("mal", rownames(floridae_CIs)),])),
                      rep("fuscus", times = nrow(fuscus_CIs[grep("mal", rownames(fuscus_CIs)),])),
                      rep("scovelli", times = nrow(scovelli_CIs[grep("mal", rownames(scovelli_CIs)),])))

male_CIs[,1:3]<-round(male_CIs[,1:3],6)
kable(male_CIs)

```

